package heliecp.roadchina.item;

import heliecp.roadchina.Utils;
import heliecp.roadchina.block.BlockRegistry;
import heliecp.roadchina.group.ModGroup;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ItemRegistry
{
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Utils.MOD_ID);

    public static final RegistryObject<Item> wrench = ITEMS.register("wrench", Wrench::new);

    public static final RegistryObject<Item> asphaltRoad = ITEMS.register("asphalt_road", () -> new BlockItem(BlockRegistry.asphaltRoad.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteAsphaltRoad = ITEMS.register("white_asphalt_road", () -> new BlockItem(BlockRegistry.whiteAsphaltRoad.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> yellowAsphaltRoad = ITEMS.register("yellow_asphalt_road", () -> new BlockItem(BlockRegistry.yellowAsphaltRoad.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));

    public static final RegistryObject<Item> whiteLine1 = ITEMS.register("white_line_1", () -> new BlockItem(BlockRegistry.whiteLine1.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine2 = ITEMS.register("white_line_2", () -> new BlockItem(BlockRegistry.whiteLine2.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine3 = ITEMS.register("white_line_3", () -> new BlockItem(BlockRegistry.whiteLine3.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine4 = ITEMS.register("white_line_4", () -> new BlockItem(BlockRegistry.whiteLine4.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine5 = ITEMS.register("white_line_5", () -> new BlockItem(BlockRegistry.whiteLine5.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine6 = ITEMS.register("white_line_6", () -> new BlockItem(BlockRegistry.whiteLine6.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine7 = ITEMS.register("white_line_7", () -> new BlockItem(BlockRegistry.whiteLine7.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine8 = ITEMS.register("white_line_8", () -> new BlockItem(BlockRegistry.whiteLine8.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine9a = ITEMS.register("white_line_9a", () -> new BlockItem(BlockRegistry.whiteLine9a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine9b = ITEMS.register("white_line_9b", () -> new BlockItem(BlockRegistry.whiteLine9b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine10a = ITEMS.register("white_line_10a", () -> new BlockItem(BlockRegistry.whiteLine10a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine10b = ITEMS.register("white_line_10b", () -> new BlockItem(BlockRegistry.whiteLine10b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine11a = ITEMS.register("white_line_11a", () -> new BlockItem(BlockRegistry.whiteLine11a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine11b = ITEMS.register("white_line_11b", () -> new BlockItem(BlockRegistry.whiteLine11b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine12a = ITEMS.register("white_line_12a", () -> new BlockItem(BlockRegistry.whiteLine12a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine12b = ITEMS.register("white_line_12b", () -> new BlockItem(BlockRegistry.whiteLine12b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine13 = ITEMS.register("white_line_13", () -> new BlockItem(BlockRegistry.whiteLine13.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine14 = ITEMS.register("white_line_14", () -> new BlockItem(BlockRegistry.whiteLine14.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine15 = ITEMS.register("white_line_15", () -> new BlockItem(BlockRegistry.whiteLine15.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine16a = ITEMS.register("white_line_16a", () -> new BlockItem(BlockRegistry.whiteLine16a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine16b = ITEMS.register("white_line_16b", () -> new BlockItem(BlockRegistry.whiteLine16b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine17a = ITEMS.register("white_line_17a", () -> new BlockItem(BlockRegistry.whiteLine17a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine17b = ITEMS.register("white_line_17b", () -> new BlockItem(BlockRegistry.whiteLine17b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine18a = ITEMS.register("white_line_18a", () -> new BlockItem(BlockRegistry.whiteLine18a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine18b = ITEMS.register("white_line_18b", () -> new BlockItem(BlockRegistry.whiteLine18b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine19a = ITEMS.register("white_line_19a", () -> new BlockItem(BlockRegistry.whiteLine19a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine19b = ITEMS.register("white_line_19b", () -> new BlockItem(BlockRegistry.whiteLine19b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine20a = ITEMS.register("white_line_20a", () -> new BlockItem(BlockRegistry.whiteLine20a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine20b = ITEMS.register("white_line_20b", () -> new BlockItem(BlockRegistry.whiteLine20b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine21a = ITEMS.register("white_line_21a", () -> new BlockItem(BlockRegistry.whiteLine21a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine21b = ITEMS.register("white_line_21b", () -> new BlockItem(BlockRegistry.whiteLine21b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine22a = ITEMS.register("white_line_22a", () -> new BlockItem(BlockRegistry.whiteLine22a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine22b = ITEMS.register("white_line_22b", () -> new BlockItem(BlockRegistry.whiteLine22b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine23a = ITEMS.register("white_line_23a", () -> new BlockItem(BlockRegistry.whiteLine23a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine23b = ITEMS.register("white_line_23b", () -> new BlockItem(BlockRegistry.whiteLine23b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine23c = ITEMS.register("white_line_23c", () -> new BlockItem(BlockRegistry.whiteLine23c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine24 = ITEMS.register("white_line_24", () -> new BlockItem(BlockRegistry.whiteLine24.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine25 = ITEMS.register("white_line_25", () -> new BlockItem(BlockRegistry.whiteLine25.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine26a = ITEMS.register("white_line_26a", () -> new BlockItem(BlockRegistry.whiteLine26a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine26b = ITEMS.register("white_line_26b", () -> new BlockItem(BlockRegistry.whiteLine26b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine26c = ITEMS.register("white_line_26c", () -> new BlockItem(BlockRegistry.whiteLine26c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine27a = ITEMS.register("white_line_27a", () -> new BlockItem(BlockRegistry.whiteLine27a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine27b = ITEMS.register("white_line_27b", () -> new BlockItem(BlockRegistry.whiteLine27b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine27c = ITEMS.register("white_line_27c", () -> new BlockItem(BlockRegistry.whiteLine27c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine28 = ITEMS.register("white_line_28", () -> new BlockItem(BlockRegistry.whiteLine28.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine29a = ITEMS.register("white_line_29a", () -> new BlockItem(BlockRegistry.whiteLine29a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine29b = ITEMS.register("white_line_29b", () -> new BlockItem(BlockRegistry.whiteLine29b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine29c = ITEMS.register("white_line_29c", () -> new BlockItem(BlockRegistry.whiteLine29c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine30a = ITEMS.register("white_line_30a", () -> new BlockItem(BlockRegistry.whiteLine30a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine30b = ITEMS.register("white_line_30b", () -> new BlockItem(BlockRegistry.whiteLine30b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine30c = ITEMS.register("white_line_30c", () -> new BlockItem(BlockRegistry.whiteLine30c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine31a = ITEMS.register("white_line_31a", () -> new BlockItem(BlockRegistry.whiteLine31a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine31b = ITEMS.register("white_line_31b", () -> new BlockItem(BlockRegistry.whiteLine31b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine31c = ITEMS.register("white_line_31c", () -> new BlockItem(BlockRegistry.whiteLine31c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine32 = ITEMS.register("white_line_32", () -> new BlockItem(BlockRegistry.whiteLine32.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine33a = ITEMS.register("white_line_33a", () -> new BlockItem(BlockRegistry.whiteLine33a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine33b = ITEMS.register("white_line_33b", () -> new BlockItem(BlockRegistry.whiteLine33b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine34 = ITEMS.register("white_line_34", () -> new BlockItem(BlockRegistry.whiteLine34.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine35 = ITEMS.register("white_line_35", () -> new BlockItem(BlockRegistry.whiteLine35.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine36 = ITEMS.register("white_line_36", () -> new BlockItem(BlockRegistry.whiteLine36.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine37a = ITEMS.register("white_line_37a", () -> new BlockItem(BlockRegistry.whiteLine37a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine37b = ITEMS.register("white_line_37b", () -> new BlockItem(BlockRegistry.whiteLine37b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine37c = ITEMS.register("white_line_37c", () -> new BlockItem(BlockRegistry.whiteLine37c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine37d = ITEMS.register("white_line_37d", () -> new BlockItem(BlockRegistry.whiteLine37d.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine38a = ITEMS.register("white_line_38a", () -> new BlockItem(BlockRegistry.whiteLine38a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine38b = ITEMS.register("white_line_38b", () -> new BlockItem(BlockRegistry.whiteLine38b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine38c = ITEMS.register("white_line_38c", () -> new BlockItem(BlockRegistry.whiteLine38c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine38d = ITEMS.register("white_line_38d", () -> new BlockItem(BlockRegistry.whiteLine38d.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine39a = ITEMS.register("white_line_39a", () -> new BlockItem(BlockRegistry.whiteLine39a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine39b = ITEMS.register("white_line_39b", () -> new BlockItem(BlockRegistry.whiteLine39b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine39c = ITEMS.register("white_line_39c", () -> new BlockItem(BlockRegistry.whiteLine39c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine39d = ITEMS.register("white_line_39d", () -> new BlockItem(BlockRegistry.whiteLine39d.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine40a = ITEMS.register("white_line_40a", () -> new BlockItem(BlockRegistry.whiteLine40a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine40b = ITEMS.register("white_line_40b", () -> new BlockItem(BlockRegistry.whiteLine40b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine40c = ITEMS.register("white_line_40c", () -> new BlockItem(BlockRegistry.whiteLine40c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine40d = ITEMS.register("white_line_40d", () -> new BlockItem(BlockRegistry.whiteLine40d.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine41a = ITEMS.register("white_line_41a", () -> new BlockItem(BlockRegistry.whiteLine41a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine41b = ITEMS.register("white_line_41b", () -> new BlockItem(BlockRegistry.whiteLine41b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine41c = ITEMS.register("white_line_41c", () -> new BlockItem(BlockRegistry.whiteLine41c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine41d = ITEMS.register("white_line_41d", () -> new BlockItem(BlockRegistry.whiteLine41d.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine42a = ITEMS.register("white_line_42a", () -> new BlockItem(BlockRegistry.whiteLine42a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine42b = ITEMS.register("white_line_42b", () -> new BlockItem(BlockRegistry.whiteLine42b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine42c = ITEMS.register("white_line_42c", () -> new BlockItem(BlockRegistry.whiteLine42c.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine42d = ITEMS.register("white_line_42d", () -> new BlockItem(BlockRegistry.whiteLine42d.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine43a = ITEMS.register("white_line_43a", () -> new BlockItem(BlockRegistry.whiteLine43a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine43b = ITEMS.register("white_line_43b", () -> new BlockItem(BlockRegistry.whiteLine43b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine44 = ITEMS.register("white_line_44", () -> new BlockItem(BlockRegistry.whiteLine44.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine45 = ITEMS.register("white_line_45", () -> new BlockItem(BlockRegistry.whiteLine45.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine46 = ITEMS.register("white_line_46", () -> new BlockItem(BlockRegistry.whiteLine46.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine47a = ITEMS.register("white_line_47a", () -> new BlockItem(BlockRegistry.whiteLine47a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine47b = ITEMS.register("white_line_47b", () -> new BlockItem(BlockRegistry.whiteLine47b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine48a = ITEMS.register("white_line_48a", () -> new BlockItem(BlockRegistry.whiteLine48a.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine48b = ITEMS.register("white_line_48b", () -> new BlockItem(BlockRegistry.whiteLine48b.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));

    public static final RegistryObject<Item> yellowLine1 = ITEMS.register("yellow_line_1", () -> new BlockItem(BlockRegistry.yellowLine1.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine2 = ITEMS.register("yellow_line_2", () -> new BlockItem(BlockRegistry.yellowLine2.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine3 = ITEMS.register("yellow_line_3", () -> new BlockItem(BlockRegistry.yellowLine3.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine4 = ITEMS.register("yellow_line_4", () -> new BlockItem(BlockRegistry.yellowLine4.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine5 = ITEMS.register("yellow_line_5", () -> new BlockItem(BlockRegistry.yellowLine5.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine6 = ITEMS.register("yellow_line_6", () -> new BlockItem(BlockRegistry.yellowLine6.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine7 = ITEMS.register("yellow_line_7", () -> new BlockItem(BlockRegistry.yellowLine7.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine8 = ITEMS.register("yellow_line_8", () -> new BlockItem(BlockRegistry.yellowLine8.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine9 = ITEMS.register("yellow_line_9", () -> new BlockItem(BlockRegistry.yellowLine9.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine10a = ITEMS.register("yellow_line_10a", () -> new BlockItem(BlockRegistry.yellowLine10a.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine10b = ITEMS.register("yellow_line_10b", () -> new BlockItem(BlockRegistry.yellowLine10b.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine11a = ITEMS.register("yellow_line_11a", () -> new BlockItem(BlockRegistry.yellowLine11a.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine11b = ITEMS.register("yellow_line_11b", () -> new BlockItem(BlockRegistry.yellowLine11b.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine12a = ITEMS.register("yellow_line_12a", () -> new BlockItem(BlockRegistry.yellowLine12a.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine12b = ITEMS.register("yellow_line_12b", () -> new BlockItem(BlockRegistry.yellowLine12b.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));

    public static final RegistryObject<Item> whiteYellowLine1a = ITEMS.register("white_yellow_line_1a", () -> new BlockItem(BlockRegistry.whiteYellowLine1a.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine1b = ITEMS.register("white_yellow_line_1b", () -> new BlockItem(BlockRegistry.whiteYellowLine1b.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine2a = ITEMS.register("white_yellow_line_2a", () -> new BlockItem(BlockRegistry.whiteYellowLine2a.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine2b = ITEMS.register("white_yellow_line_2b", () -> new BlockItem(BlockRegistry.whiteYellowLine2b.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine3a = ITEMS.register("white_yellow_line_3a", () -> new BlockItem(BlockRegistry.whiteYellowLine3a.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine3b = ITEMS.register("white_yellow_line_3b", () -> new BlockItem(BlockRegistry.whiteYellowLine3b.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine4 = ITEMS.register("white_yellow_line_4", () -> new BlockItem(BlockRegistry.whiteYellowLine4.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine5a = ITEMS.register("white_yellow_line_5a", () -> new BlockItem(BlockRegistry.whiteYellowLine5a.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine5b = ITEMS.register("white_yellow_line_5b", () -> new BlockItem(BlockRegistry.whiteYellowLine5b.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine5c = ITEMS.register("white_yellow_line_5c", () -> new BlockItem(BlockRegistry.whiteYellowLine5c.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine6a = ITEMS.register("white_yellow_line_6a", () -> new BlockItem(BlockRegistry.whiteYellowLine6a.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine6b = ITEMS.register("white_yellow_line_6b", () -> new BlockItem(BlockRegistry.whiteYellowLine6b.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine6c = ITEMS.register("white_yellow_line_6c", () -> new BlockItem(BlockRegistry.whiteYellowLine6c.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine7a = ITEMS.register("white_yellow_line_7a", () -> new BlockItem(BlockRegistry.whiteYellowLine7a.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine7b = ITEMS.register("white_yellow_line_7b", () -> new BlockItem(BlockRegistry.whiteYellowLine7b.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine7c = ITEMS.register("white_yellow_line_7c", () -> new BlockItem(BlockRegistry.whiteYellowLine7c.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine8 = ITEMS.register("white_yellow_line_8", () -> new BlockItem(BlockRegistry.whiteYellowLine8.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));

    public static final RegistryObject<Item> roadchina = ITEMS.register("roadchina", () -> new BlockItem(BlockRegistry.roadchina.get(), new Item.Properties()));

    public static final RegistryObject<Item> asphaltRoadSlab = ITEMS.register("asphalt_road_slab", () -> new BlockItem(BlockRegistry.asphaltRoadSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteAsphaltRoadSlab = ITEMS.register("white_asphalt_road_slab", () -> new BlockItem(BlockRegistry.whiteAsphaltRoadSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> yellowAsphaltRoadSlab = ITEMS.register("yellow_asphalt_road_slab", () -> new BlockItem(BlockRegistry.yellowAsphaltRoadSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));

    public static final RegistryObject<Item> whiteLine1Slab = ITEMS.register("white_line_1_slab", () -> new BlockItem(BlockRegistry.whiteLine1Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine2Slab = ITEMS.register("white_line_2_slab", () -> new BlockItem(BlockRegistry.whiteLine2Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine3Slab = ITEMS.register("white_line_3_slab", () -> new BlockItem(BlockRegistry.whiteLine3Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine4Slab = ITEMS.register("white_line_4_slab", () -> new BlockItem(BlockRegistry.whiteLine4Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine5Slab = ITEMS.register("white_line_5_slab", () -> new BlockItem(BlockRegistry.whiteLine5Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine6Slab = ITEMS.register("white_line_6_slab", () -> new BlockItem(BlockRegistry.whiteLine6Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine7Slab = ITEMS.register("white_line_7_slab", () -> new BlockItem(BlockRegistry.whiteLine7Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine8Slab = ITEMS.register("white_line_8_slab", () -> new BlockItem(BlockRegistry.whiteLine8Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine9aSlab = ITEMS.register("white_line_9a_slab", () -> new BlockItem(BlockRegistry.whiteLine9aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine9bSlab = ITEMS.register("white_line_9b_slab", () -> new BlockItem(BlockRegistry.whiteLine9bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine10aSlab = ITEMS.register("white_line_10a_slab", () -> new BlockItem(BlockRegistry.whiteLine10aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine10bSlab = ITEMS.register("white_line_10b_slab", () -> new BlockItem(BlockRegistry.whiteLine10bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine11aSlab = ITEMS.register("white_line_11a_slab", () -> new BlockItem(BlockRegistry.whiteLine11aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine11bSlab = ITEMS.register("white_line_11b_slab", () -> new BlockItem(BlockRegistry.whiteLine11bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine12aSlab = ITEMS.register("white_line_12a_slab", () -> new BlockItem(BlockRegistry.whiteLine12aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine12bSlab = ITEMS.register("white_line_12b_slab", () -> new BlockItem(BlockRegistry.whiteLine12bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine13Slab = ITEMS.register("white_line_13_slab", () -> new BlockItem(BlockRegistry.whiteLine13Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine14Slab = ITEMS.register("white_line_14_slab", () -> new BlockItem(BlockRegistry.whiteLine14Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine15Slab = ITEMS.register("white_line_15_slab", () -> new BlockItem(BlockRegistry.whiteLine15Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine16aSlab = ITEMS.register("white_line_16a_slab", () -> new BlockItem(BlockRegistry.whiteLine16aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine16bSlab = ITEMS.register("white_line_16b_slab", () -> new BlockItem(BlockRegistry.whiteLine16bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine17aSlab = ITEMS.register("white_line_17a_slab", () -> new BlockItem(BlockRegistry.whiteLine17aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine17bSlab = ITEMS.register("white_line_17b_slab", () -> new BlockItem(BlockRegistry.whiteLine17bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine18aSlab = ITEMS.register("white_line_18a_slab", () -> new BlockItem(BlockRegistry.whiteLine18aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine18bSlab = ITEMS.register("white_line_18b_slab", () -> new BlockItem(BlockRegistry.whiteLine18bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine19aSlab = ITEMS.register("white_line_19a_slab", () -> new BlockItem(BlockRegistry.whiteLine19aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine19bSlab = ITEMS.register("white_line_19b_slab", () -> new BlockItem(BlockRegistry.whiteLine19bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine20aSlab = ITEMS.register("white_line_20a_slab", () -> new BlockItem(BlockRegistry.whiteLine20aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine20bSlab = ITEMS.register("white_line_20b_slab", () -> new BlockItem(BlockRegistry.whiteLine20bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine21aSlab = ITEMS.register("white_line_21a_slab", () -> new BlockItem(BlockRegistry.whiteLine21aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine21bSlab = ITEMS.register("white_line_21b_slab", () -> new BlockItem(BlockRegistry.whiteLine21bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine22aSlab = ITEMS.register("white_line_22a_slab", () -> new BlockItem(BlockRegistry.whiteLine22aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine22bSlab = ITEMS.register("white_line_22b_slab", () -> new BlockItem(BlockRegistry.whiteLine22bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine23aSlab = ITEMS.register("white_line_23a_slab", () -> new BlockItem(BlockRegistry.whiteLine23aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine23bSlab = ITEMS.register("white_line_23b_slab", () -> new BlockItem(BlockRegistry.whiteLine23bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine23cSlab = ITEMS.register("white_line_23c_slab", () -> new BlockItem(BlockRegistry.whiteLine23cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine24Slab = ITEMS.register("white_line_24_slab", () -> new BlockItem(BlockRegistry.whiteLine24Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine25Slab = ITEMS.register("white_line_25_slab", () -> new BlockItem(BlockRegistry.whiteLine25Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine26aSlab = ITEMS.register("white_line_26a_slab", () -> new BlockItem(BlockRegistry.whiteLine26aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine26bSlab = ITEMS.register("white_line_26b_slab", () -> new BlockItem(BlockRegistry.whiteLine26bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine26cSlab = ITEMS.register("white_line_26c_slab", () -> new BlockItem(BlockRegistry.whiteLine26cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine27aSlab = ITEMS.register("white_line_27a_slab", () -> new BlockItem(BlockRegistry.whiteLine27aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine27bSlab = ITEMS.register("white_line_27b_slab", () -> new BlockItem(BlockRegistry.whiteLine27bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine27cSlab = ITEMS.register("white_line_27c_slab", () -> new BlockItem(BlockRegistry.whiteLine27cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine28Slab = ITEMS.register("white_line_28_slab", () -> new BlockItem(BlockRegistry.whiteLine28Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine29aSlab = ITEMS.register("white_line_29a_slab", () -> new BlockItem(BlockRegistry.whiteLine29aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine29bSlab = ITEMS.register("white_line_29b_slab", () -> new BlockItem(BlockRegistry.whiteLine29bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine29cSlab = ITEMS.register("white_line_29c_slab", () -> new BlockItem(BlockRegistry.whiteLine29cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine30aSlab = ITEMS.register("white_line_30a_slab", () -> new BlockItem(BlockRegistry.whiteLine30aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine30bSlab = ITEMS.register("white_line_30b_slab", () -> new BlockItem(BlockRegistry.whiteLine30bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine30cSlab = ITEMS.register("white_line_30c_slab", () -> new BlockItem(BlockRegistry.whiteLine30cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine31aSlab = ITEMS.register("white_line_31a_slab", () -> new BlockItem(BlockRegistry.whiteLine31aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine31bSlab = ITEMS.register("white_line_31b_slab", () -> new BlockItem(BlockRegistry.whiteLine31bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine31cSlab = ITEMS.register("white_line_31c_slab", () -> new BlockItem(BlockRegistry.whiteLine31cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine32Slab = ITEMS.register("white_line_32_slab", () -> new BlockItem(BlockRegistry.whiteLine32Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine33aSlab = ITEMS.register("white_line_33a_slab", () -> new BlockItem(BlockRegistry.whiteLine33aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine33bSlab = ITEMS.register("white_line_33b_slab", () -> new BlockItem(BlockRegistry.whiteLine33bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine34Slab = ITEMS.register("white_line_34_slab", () -> new BlockItem(BlockRegistry.whiteLine34Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine35Slab = ITEMS.register("white_line_35_slab", () -> new BlockItem(BlockRegistry.whiteLine35Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine36Slab = ITEMS.register("white_line_36_slab", () -> new BlockItem(BlockRegistry.whiteLine36Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine37aSlab = ITEMS.register("white_line_37a_slab", () -> new BlockItem(BlockRegistry.whiteLine37aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine37bSlab = ITEMS.register("white_line_37b_slab", () -> new BlockItem(BlockRegistry.whiteLine37bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine37cSlab = ITEMS.register("white_line_37c_slab", () -> new BlockItem(BlockRegistry.whiteLine37cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine37dSlab = ITEMS.register("white_line_37d_slab", () -> new BlockItem(BlockRegistry.whiteLine37dSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine38aSlab = ITEMS.register("white_line_38a_slab", () -> new BlockItem(BlockRegistry.whiteLine38aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine38bSlab = ITEMS.register("white_line_38b_slab", () -> new BlockItem(BlockRegistry.whiteLine38bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine38cSlab = ITEMS.register("white_line_38c_slab", () -> new BlockItem(BlockRegistry.whiteLine38cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine38dSlab = ITEMS.register("white_line_38d_slab", () -> new BlockItem(BlockRegistry.whiteLine38dSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine39aSlab = ITEMS.register("white_line_39a_slab", () -> new BlockItem(BlockRegistry.whiteLine39aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine39bSlab = ITEMS.register("white_line_39b_slab", () -> new BlockItem(BlockRegistry.whiteLine39bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine39cSlab = ITEMS.register("white_line_39c_slab", () -> new BlockItem(BlockRegistry.whiteLine39cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine39dSlab = ITEMS.register("white_line_39d_slab", () -> new BlockItem(BlockRegistry.whiteLine39dSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine40aSlab = ITEMS.register("white_line_40a_slab", () -> new BlockItem(BlockRegistry.whiteLine40aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine40bSlab = ITEMS.register("white_line_40b_slab", () -> new BlockItem(BlockRegistry.whiteLine40bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine40cSlab = ITEMS.register("white_line_40c_slab", () -> new BlockItem(BlockRegistry.whiteLine40cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine40dSlab = ITEMS.register("white_line_40d_slab", () -> new BlockItem(BlockRegistry.whiteLine40dSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine41aSlab = ITEMS.register("white_line_41a_slab", () -> new BlockItem(BlockRegistry.whiteLine41aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine41bSlab = ITEMS.register("white_line_41b_slab", () -> new BlockItem(BlockRegistry.whiteLine41bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine41cSlab = ITEMS.register("white_line_41c_slab", () -> new BlockItem(BlockRegistry.whiteLine41cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine41dSlab = ITEMS.register("white_line_41d_slab", () -> new BlockItem(BlockRegistry.whiteLine41dSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine42aSlab = ITEMS.register("white_line_42a_slab", () -> new BlockItem(BlockRegistry.whiteLine42aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine42bSlab = ITEMS.register("white_line_42b_slab", () -> new BlockItem(BlockRegistry.whiteLine42bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine42cSlab = ITEMS.register("white_line_42c_slab", () -> new BlockItem(BlockRegistry.whiteLine42cSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine42dSlab = ITEMS.register("white_line_42d_slab", () -> new BlockItem(BlockRegistry.whiteLine42dSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine43aSlab = ITEMS.register("white_line_43a_slab", () -> new BlockItem(BlockRegistry.whiteLine43aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine43bSlab = ITEMS.register("white_line_43b_slab", () -> new BlockItem(BlockRegistry.whiteLine43bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine44Slab = ITEMS.register("white_line_44_slab", () -> new BlockItem(BlockRegistry.whiteLine44Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine45Slab = ITEMS.register("white_line_45_slab", () -> new BlockItem(BlockRegistry.whiteLine45Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine46Slab = ITEMS.register("white_line_46_slab", () -> new BlockItem(BlockRegistry.whiteLine46Slab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine47aSlab = ITEMS.register("white_line_47a_slab", () -> new BlockItem(BlockRegistry.whiteLine47aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine47bSlab = ITEMS.register("white_line_47b_slab", () -> new BlockItem(BlockRegistry.whiteLine47bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine48aSlab = ITEMS.register("white_line_48a_slab", () -> new BlockItem(BlockRegistry.whiteLine48aSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));
    public static final RegistryObject<Item> whiteLine48bSlab = ITEMS.register("white_line_48b_slab", () -> new BlockItem(BlockRegistry.whiteLine48bSlab.get(), new Item.Properties().tab(ModGroup.WHITE_LINE_GROUP)));

    public static final RegistryObject<Item> yellowLine1Slab = ITEMS.register("yellow_line_1_slab", () -> new BlockItem(BlockRegistry.yellowLine1Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine2Slab = ITEMS.register("yellow_line_2_slab", () -> new BlockItem(BlockRegistry.yellowLine2Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine3Slab = ITEMS.register("yellow_line_3_slab", () -> new BlockItem(BlockRegistry.yellowLine3Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine4Slab = ITEMS.register("yellow_line_4_slab", () -> new BlockItem(BlockRegistry.yellowLine4Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine5Slab = ITEMS.register("yellow_line_5_slab", () -> new BlockItem(BlockRegistry.yellowLine5Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine6Slab = ITEMS.register("yellow_line_6_slab", () -> new BlockItem(BlockRegistry.yellowLine6Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine7Slab = ITEMS.register("yellow_line_7_slab", () -> new BlockItem(BlockRegistry.yellowLine7Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine8Slab = ITEMS.register("yellow_line_8_slab", () -> new BlockItem(BlockRegistry.yellowLine8Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine9Slab = ITEMS.register("yellow_line_9_slab", () -> new BlockItem(BlockRegistry.yellowLine9Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine10aSlab = ITEMS.register("yellow_line_10a_slab", () -> new BlockItem(BlockRegistry.yellowLine10aSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine10bSlab = ITEMS.register("yellow_line_10b_slab", () -> new BlockItem(BlockRegistry.yellowLine10bSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine11aSlab = ITEMS.register("yellow_line_11a_slab", () -> new BlockItem(BlockRegistry.yellowLine11aSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine11bSlab = ITEMS.register("yellow_line_11b_slab", () -> new BlockItem(BlockRegistry.yellowLine11bSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine12aSlab = ITEMS.register("yellow_line_12a_slab", () -> new BlockItem(BlockRegistry.yellowLine12aSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> yellowLine12bSlab = ITEMS.register("yellow_line_12b_slab", () -> new BlockItem(BlockRegistry.yellowLine12bSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));

    public static final RegistryObject<Item> whiteYellowLine1aSlab = ITEMS.register("white_yellow_line_1a_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine1aSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine1bSlab = ITEMS.register("white_yellow_line_1b_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine1bSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine2aSlab = ITEMS.register("white_yellow_line_2a_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine2aSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine2bSlab = ITEMS.register("white_yellow_line_2b_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine2bSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine3aSlab = ITEMS.register("white_yellow_line_3a_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine3aSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine3bSlab = ITEMS.register("white_yellow_line_3b_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine3bSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine4Slab = ITEMS.register("white_yellow_line_4_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine4Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine5aSlab = ITEMS.register("white_yellow_line_5a_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine5aSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine5bSlab = ITEMS.register("white_yellow_line_5b_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine5bSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine5cSlab = ITEMS.register("white_yellow_line_5c_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine5cSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine6aSlab = ITEMS.register("white_yellow_line_6a_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine6aSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine6bSlab = ITEMS.register("white_yellow_line_6b_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine6bSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine6cSlab = ITEMS.register("white_yellow_line_6c_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine6cSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine7aSlab = ITEMS.register("white_yellow_line_7a_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine7aSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine7bSlab = ITEMS.register("white_yellow_line_7b_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine7bSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine7cSlab = ITEMS.register("white_yellow_line_7c_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine7cSlab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));
    public static final RegistryObject<Item> whiteYellowLine8Slab = ITEMS.register("white_yellow_line_8_slab", () -> new BlockItem(BlockRegistry.whiteYellowLine8Slab.get(), new Item.Properties().tab(ModGroup.YELLOW_LINE_GROUP)));

    public static final RegistryObject<Item> whiteArrow1 = ITEMS.register("white_arrow_1", () -> new BlockItem(BlockRegistry.whiteArrow1.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteArrow2a = ITEMS.register("white_arrow_2a", () -> new BlockItem(BlockRegistry.whiteArrow2a.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteArrow2b = ITEMS.register("white_arrow_2b", () -> new BlockItem(BlockRegistry.whiteArrow2b.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteArrow3a = ITEMS.register("white_arrow_3a", () -> new BlockItem(BlockRegistry.whiteArrow3a.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteArrow3b = ITEMS.register("white_arrow_3b", () -> new BlockItem(BlockRegistry.whiteArrow3b.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteArrow4 = ITEMS.register("white_arrow_4", () -> new BlockItem(BlockRegistry.whiteArrow4.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteArrow5a = ITEMS.register("white_arrow_5a", () -> new BlockItem(BlockRegistry.whiteArrow5a.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteArrow5b = ITEMS.register("white_arrow_5b", () -> new BlockItem(BlockRegistry.whiteArrow5b.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteArrow6 = ITEMS.register("white_arrow_6", () -> new BlockItem(BlockRegistry.whiteArrow6.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteArrow7 = ITEMS.register("white_arrow_7", () -> new BlockItem(BlockRegistry.whiteArrow7.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteArrow8 = ITEMS.register("white_arrow_8", () -> new BlockItem(BlockRegistry.whiteArrow8.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));

    public static final RegistryObject<Item> whiteMarking1 = ITEMS.register("white_marking_1", () -> new BlockItem(BlockRegistry.whiteMarking1.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteMarking2 = ITEMS.register("white_marking_2", () -> new BlockItem(BlockRegistry.whiteMarking2.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteMarking3 = ITEMS.register("white_marking_3", () -> new BlockItem(BlockRegistry.whiteMarking3.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteMarking4 = ITEMS.register("white_marking_4", () -> new BlockItem(BlockRegistry.whiteMarking4.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteMarking5 = ITEMS.register("white_marking_5", () -> new BlockItem(BlockRegistry.whiteMarking5.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteMarking6 = ITEMS.register("white_marking_6", () -> new BlockItem(BlockRegistry.whiteMarking6.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));
    public static final RegistryObject<Item> whiteMarkingTing = ITEMS.register("white_marking_ting", () -> new BlockItem(BlockRegistry.whiteMarkingTing.get(), new Item.Properties().tab(ModGroup.MARKING_GROUP)));

    public static final RegistryObject<Item> thinPostGray = ITEMS.register("thin_post_gray", () -> new BlockItem(BlockRegistry.thinPostGray.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> thinPostSilver = ITEMS.register("thin_post_silver", () -> new BlockItem(BlockRegistry.thinPostSilver.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));

    public static final RegistryObject<Item> thinPostGrayNC1 = ITEMS.register("thin_post_gray_nc1", () -> new BlockItem(BlockRegistry.thinPostGrayNC1.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> thinPostSilverNC1 = ITEMS.register("thin_post_silver_nc1", () -> new BlockItem(BlockRegistry.thinPostSilverNC1.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));

    public static final RegistryObject<Item> thinPostGrayBase = ITEMS.register("thin_post_gray_base", () -> new BlockItem(BlockRegistry.thinPostGrayBase.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> thinPostSilverBase = ITEMS.register("thin_post_silver_base", () -> new BlockItem(BlockRegistry.thinPostSilverBase.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));

    public static final RegistryObject<Item> postBlack = ITEMS.register("post_black", () -> new BlockItem(BlockRegistry.postBlack.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> postGray = ITEMS.register("post_gray", () -> new BlockItem(BlockRegistry.postGray.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> postSilver = ITEMS.register("post_silver", () -> new BlockItem(BlockRegistry.postSilver.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> postBlue = ITEMS.register("post_blue", () -> new BlockItem(BlockRegistry.postBlue.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> postWhite = ITEMS.register("post_white", () -> new BlockItem(BlockRegistry.postWhite.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));

    public static final RegistryObject<Item> postBlackNC1 = ITEMS.register("post_black_nc1", () -> new BlockItem(BlockRegistry.postBlackNC1.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> postGrayNC1 = ITEMS.register("post_gray_nc1", () -> new BlockItem(BlockRegistry.postGrayNC1.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> postSilverNC1 = ITEMS.register("post_silver_nc1", () -> new BlockItem(BlockRegistry.postSilverNC1.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> postBlueNC1 = ITEMS.register("post_blue_nc1", () -> new BlockItem(BlockRegistry.postBlueNC1.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> postWhiteNC1 = ITEMS.register("post_white_nc1", () -> new BlockItem(BlockRegistry.postWhiteNC1.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));

    public static final RegistryObject<Item> postGrayBase = ITEMS.register("post_gray_base", () -> new BlockItem(BlockRegistry.postGrayBase.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
    public static final RegistryObject<Item> postSilverBase = ITEMS.register("post_silver_base", () -> new BlockItem(BlockRegistry.postSilverBase.get(), new Item.Properties().tab(ModGroup.ROAD_SIGN_GROUP)));
}
