modLoader="javafml"
loaderVersion="[44,45]"
license="All rights reserved"

[[mods]]
modId="roadchina"
version="23m05d"
displayName="Road China"
logoFile="icon.png"
credits="Heliecp"
authors="Heliecp"
description='''
This is a chinese style road mod.'''

[[dependencies.roadchina]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.roadchina]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
