modLoader="javafml"
loaderVersion="[37,)"
license="GNU GPLv3"

[[mods]]
modId="roadchina"
version="23m05a"
displayName="Road China"
logoFile="icon.png"
credits="Heliecp"
authors="Heliecp"
description='''
This is a chinese style road mod.
'''

[[dependencies.roadchina]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.roadchina]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
