modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPLv3"

[[mods]]
modId="roadchina"
version="23m03d"
displayName="Road China"
logoFile="icon.png"
credits="Heliecp"
authors="Heliecp"
description='''
This is a chinese style road mod.
'''

[[dependencies.roadchina]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roadchina]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"