modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
modId="roadchina"
version="23m05d"
displayName="Road China"
logoFile="icon.png"
credits="Heliecp"
authors="Heliecp"
description='''
This is a chinese style road mod.'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
